version: '3'
services:

  #PHP Service
  app-wtb:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: digitalocean.com/php
    container_name: app-wtb
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-wtb-network

  #Nginx Service
  nginx-wtb:
    image: nginx:alpine
    container_name: nginx-wtb
    restart: unless-stopped
    tty: true
    ports:
      - ${NGINX_PORT_80}:80
      - ${NGINX_PORT_443}:443
    volumes:
      - ../:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-wtb-network

  #MySQL Service
  db-wtb:
    image: mysql:5.7.22
    container_name: db-wtb
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 43562345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-wtb-network

#Docker Networks
networks:
  app-wtb-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
